# Generated by Django 6.0.2 on 2026-02-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_assignment_assignment_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teacher'},
        ),
    ]
