# Generated by Django 6.0.2 on 2026-02-07 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_chapter_course_alter_exam_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlike',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_like', to='course_app.review'),
        ),
    ]
